language: java
sudo: false

env:
  global:

before_install:

install: true

script:
  - wget -nv -O sdkperf-java-latest.zip https://products.solace.com/download/SDKPERF_JAVA
  - unzip sdkperf-java-latest.zip
  - SDKPERF_HOME=`ls -d sol-sdkperf-*`
  - CURRENT_HOME=`pwd`
  - ./gradlew clean build tar
  - tar zxf build/distributions/sol-sdkperf-amqp-plugin-*.tgz --directory ${SDKPERF_HOME}/lib

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"

after_script: