sudo: false
language: java
java:
  - "1.8"

env:
  global:

before_install:

addons:
  apt:
    packages:
    - jq

install: true

script:
  - wget -nv -O sdkperf-java-latest.zip https://products.solace.com/download/SDKPERF_JAVA
  - unzip sdkperf-java-latest.zip
  - SDKPERF_HOME=`ls -d sol-sdkperf-*`
  - CURRENT_HOME=`pwd`
  - CURENT_DATE=`date -Iseconds`
  - ./gradlew clean build tar
  - tar zxf build/distributions/sol-sdkperf-amqp-plugin-*.tgz --directory ${SDKPERF_HOME}/lib
  - rm ${SDKPERF_HOME}/lib/geronimo-jms_1.1_spec-1.1.1.*
  - |
    newBrocker="$(curl --request POST --url https://console.solace.cloud/api/v0/services  -H "Authorization: Bearer ${SOLACE_CLOUD_TOKEN}"  --header 'Content-Type: application/json'   --data '{
    "name": "TestService${CURENT_DATE}",
    "datacenterId": "aws-us-east-1b",
    "partitionId": "default",
    "servicePlanId": "enterprise-nano-plan",
    "adminState": "start"
    }')"

  - serviceId=`jq '.data.serviceId' <<< $newBroker`
  - serviceId=${serviceId//\"}
  - serviceInfo="$(curl --request GET --url https://console.solace.cloud/api/v0/services/${serviceId}  -H "Authorization: Bearer ${SOLACE_CLOUD_TOKEN}"  --header 'Content-Type: application/json')"
  - AMQP_URI=`jq .data.messagingProtocols[3].endPoints[0].uris[0] <<< $serviceInfo`
  - AMQP_URI=${AMQP_URI//\"}
  - USERNAME=`jq .data.messagingProtocols[3].username <<< $serviceInfo`
  - USERNAME=${USERNAME//\"}
  - PASSWORD=`jq .data.messagingProtocols[3].password <<< $serviceInfo`
  - PASSWORD=${PASSWORD//\"}
  - test_result=`./sdkperf_java.sh -api=thirdparty -ecc=com.solacesystems.pubsub.sdkperf.jms.amqp.AmqpJms_2_0_Client -cip=${AMQP_URI} -cu=${USERNAME} -cp=${PASSWORD} -sql=testQueue -pql=testQueue -mt=persistent -mr=500 -mn=30000 -msa=500 -oc -rc=-1`
  - if [ "1" == `echo $test_result | grep -c "Messages received across all subscribers = 5000"` ]; then echo HIT; fi

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"

after_script:
 - curl --request DELETE --url https://console.solace.cloud/api/v0/services/${serviceId}  -H "Authorization: Bearer ${SOLACE_CLOUD_TOKEN}"  --header 'Content-Type: application/json'