language: java
sudo: false

env:
  global:

before_install:

install: true

script:
  - ./gradlew build

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"

after_script: